channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.29.5
  - ipython=8.22.2
  - keras=2.13.1
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.7
  - numpy=1.26.4
  - opencv=4.9.0
  - openpyxl=3.1.4
  - pandas=2.2.2
  - python=3.11.9
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - streamlit=1.37.0
  - tensorflow=2.13.1
  - tensorflow-base=2.13.1
  - tensorflow-estimator=2.13.1
